name: Express CI Pipeline

on:
  push:
    branches-ignore:
      - main
      - production
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: development

    defaults:
      run: 
        working-directory: ./test/

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: './test/package-lock.json'
          cache: 'npm'

      - name: Get .env
        run: echo "${{ secrets.ENV }}" > ./.env 

      - name: Install dependencies, build and test
        run: | 
          npm ci
          npm run build --if-present
         # npm test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build
