name: Test error

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies, build and test
        run: | 
          npm ci
          npm run build --if-present
         # npm test

      - name: Deploy to development Server
        uses: appleboy/ssh-action@master
        with:
          host: 3.38.116.144
          username: "ec2-user"
          key: ${{ secrets.PASSWORD }}
          script: |
            cat hello.txt
            ls -al

  debug:
    needs: [build]
    runs-on: ubuntu-latest

    if: ${{ failure() }}
    steps:
      - run: echo "Faild to CI"