name: Production Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: production

    defaults:
      run: 
        working-directory: ./test/

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: './test/package-lock.json'
          cache: 'npm'

      - name: Get .env
        run: echo "${{ secrets.ENV }}" > ./.env 

      - name: Install dependencies, build and test
        run: | 
          npm ci
          npm run build --if-present
          # npm test

      - name: Deploy to production Server
        uses: actions/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            git pull
            cd ${{ secrets.SERVER_DIR }}/test
            npm ci
            npm run build --if-present
            # npm test
            pm2 restart ecosystem.config.js